In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
Tesla T4


## Creating a Tensor

In [ ]:
# using empty
x=torch.empty(2,3)
print(x)

tensor([[1.8311e-12, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])


In [ ]:
# check type
print(type(x))

<class 'torch.Tensor'>


In [ ]:
# using zeros
x=torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# using ones
x=torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# using rand
x=torch.rand(2,3)
print(x)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


In [ ]:
# use of seed
torch.manual_seed(100)
x=torch.rand(2,3)
print(x)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [ ]:
# using tensor
x=torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


### Other ways


In [ ]:
# arange
x=torch.arange(0,18,2)
print(x)


tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])


In [ ]:
# using linspace
x=torch.linspace(0,18,12)
print(x)

tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])


In [ ]:
# using eye
x=torch.eye(5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
# using full
x=torch.full((2,3),5)
print(x)

tensor([[5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[767533007,         0, 665914216],
        [536870912,         0,         5]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# torch.rand_like(x)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

## Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
x=torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.rand_like(x)

tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])

In [ ]:
x=torch.tensor([1.0,2.0,3.0], dtype=torch.int32)
x

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# using to
x=torch.tensor([1,2,3])
x=x.to(torch.float32)
x

tensor([1., 2., 3.])

## Mathematical Operations

### 1. Scalar Operations

In [ ]:
X=torch.rand(2,2)
X

tensor([[0.9051, 0.5989],
        [0.4450, 0.7278]])

In [ ]:
# addition
X+1

#subtraction
X-1

#multiplication
X*1

#division
X/1

#mod
X%1

#power
X**2

tensor([[0.8192, 0.3586],
        [0.1980, 0.5297]])

### 2. Element wise operations

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)


tensor([[0.7668, 0.1659, 0.4393],
        [0.2243, 0.8935, 0.0497]])
tensor([[0.1780, 0.3011, 0.1893],
        [0.9186, 0.2131, 0.3957]])


In [ ]:
# add
torch.add(a,b)

# subtract
torch.sub(a,b)

# multiply
torch.mul(a,b)

# divide
torch.div(a,b)

# mod
torch.remainder(a,b)

# power
torch.pow(a,b)


tensor([[0.9538, 0.5823, 0.8558],
        [0.2533, 0.9763, 0.3050]])

In [ ]:
c = torch.tensor([1,-2,3,4])
d = torch.tensor([5.2,6.3,7.9,8.1])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# sign
torch.sign(c)

tensor([ 1, -1,  1,  1])

In [ ]:
# ceil
torch.ceil(c)

tensor([ 1, -2,  3,  4])

In [ ]:
# floor
torch.floor(c)

tensor([ 1, -2,  3,  4])

In [ ]:
# round
torch.round(c)

tensor([ 1, -2,  3,  4])

In [ ]:
# exp
torch.exp(c)


tensor([ 2.7183,  0.1353, 20.0855, 54.5981])

In [ ]:
# log
torch.log(c)


tensor([0.0000,    nan, 1.0986, 1.3863])

In [ ]:
# sqrt
torch.sqrt(c)

tensor([1.0000,    nan, 1.7321, 2.0000])

In [ ]:
# sin
torch.sin(c)

tensor([ 0.8415, -0.9093,  0.1411, -0.7568])

In [ ]:
# cos
torch.cos(c)

tensor([ 0.5403, -0.4161, -0.9900, -0.6536])

In [ ]:
# tan
torch.tan(c)

tensor([ 1.5574,  2.1850, -0.1425,  1.1578])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  2, -3, -4])

In [ ]:
# reciprocal
torch.reciprocal(c)

tensor([ 1.0000, -0.5000,  0.3333,  0.2500])

In [ ]:
# clamp
torch.clamp(d, min=5, max=7)

tensor([5.2000, 6.3000, 7.0000, 7.0000])

### 3. Reduction **Operation**

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[1., 2., 7.],
        [9., 2., 4.]])

In [ ]:
# sum
torch.sum(e)

#sum along columns
torch.sum(e, dim=0)

#sum along rows
torch.sum(e, dim=1)

tensor([12, 15])

In [ ]:
# mean
torch.mean(e)

#mean along columns
torch.mean(e, dim=0)

#mean along rows
torch.mean(e, dim=1)

tensor([4.6667, 1.0000])

In [ ]:
#median
torch.median(e)

#median along columns
torch.median(e, dim=0)

#median along rows
torch.median(e, dim=1)

torch.return_types.median(
values=tensor([3., 1.]),
indices=tensor([2, 0]))

In [ ]:
 # max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(1008.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.1885)

In [ ]:
# variance
torch.var(e)

tensor(10.1667)

In [ ]:
# argmax
torch.argmax(e)

tensor(3)

In [ ]:
# argmin
torch.argmin(e)

tensor(0)

### 4. Matrix Operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[6, 6, 8],
        [4, 9, 0]])
tensor([[7, 9],
        [2, 7],
        [0, 2]])


In [ ]:
# matrix multiplication
torch.mm(f,g)

tensor([[ 54, 112],
        [ 46,  99]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.t(f)

tensor([[6, 4],
        [6, 9],
        [8, 0]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[4., 4., 6.],
        [2., 1., 0.],
        [5., 1., 0.]])

In [ ]:
# determinant
torch.det(h)

tensor(-18.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 1.8626e-09, -3.3333e-01,  3.3333e-01],
        [-9.3132e-09,  1.6667e+00, -6.6667e-01],
        [ 1.6667e-01, -8.8889e-01,  2.2222e-01]])

### 5. Comparison Operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 2, 2],
        [3, 7, 1]])
tensor([[5, 0, 2],
        [3, 7, 0]])


In [ ]:
# greater than
torch.gt(i,j)

tensor([[False,  True, False],
        [False, False,  True]])

In [ ]:
# lesser than
torch.lt(i,j)

tensor([[ True, False, False],
        [False, False, False]])

In [ ]:
# equal to
torch.eq(i,j)

tensor([[False, False,  True],
        [ True,  True, False]])

In [ ]:
# not equal to
torch.ne(i,j)

tensor([[ True,  True, False],
        [False, False,  True]])

In [ ]:
# less than equal to
torch.le(i,j)


tensor([[ True, False,  True],
        [ True,  True, False]])

### 6. Special Functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[2., 5., 2.],
        [8., 0., 2.]])

In [ ]:
# log
torch.log(k)

tensor([[0.6931, 1.6094, 0.6931],
        [2.0794,   -inf, 0.6931]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[1.4142, 2.2361, 1.4142],
        [2.8284, 0.0000, 1.4142]])

In [ ]:
# exp
torch.exp(k)

tensor([[7.3891e+00, 1.4841e+02, 7.3891e+00],
        [2.9810e+03, 1.0000e+00, 7.3891e+00]])

In [ ]:
# sigmoid
torch.sigmoid(k)


tensor([[0.8808, 0.9933, 0.8808],
        [0.9997, 0.5000, 0.8808]])

In [ ]:
# relu
torch.relu(k)

tensor([[2., 5., 2.],
        [8., 0., 2.]])

In [ ]:
# softmax
torch.softmax(k, dim=1)

tensor([[4.5279e-02, 9.0944e-01, 4.5279e-02],
        [9.9719e-01, 3.3452e-04, 2.4718e-03]])

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.1719, 0.9127, 0.6818],
        [0.1953, 0.9991, 0.1133]])
tensor([[0.0135, 0.1450, 0.7819],
        [0.3134, 0.2983, 0.3436]])


In [ ]:
m.add_(n)

tensor([[0.1854, 1.0577, 1.4637],
        [0.5087, 1.2974, 0.4569]])

In [ ]:
m

tensor([[0.1854, 1.0577, 1.4637],
        [0.5087, 1.2974, 0.4569]])

In [ ]:
n

tensor([[0.0135, 0.1450, 0.7819],
        [0.3134, 0.2983, 0.3436]])

In [ ]:
torch.relu(n)

tensor([[0.0135, 0.1450, 0.7819],
        [0.3134, 0.2983, 0.3436]])

In [ ]:
m.relu_()

tensor([[0.1854, 1.0577, 1.4637],
        [0.5087, 1.2974, 0.4569]])

In [ ]:
m

tensor([[0.1854, 1.0577, 1.4637],
        [0.5087, 1.2974, 0.4569]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.2028, 0.9792, 0.4947],
        [0.3617, 0.9687, 0.0359]])

In [ ]:
a

tensor([[0.2028, 0.9792, 0.4947],
        [0.3617, 0.9687, 0.0359]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.2028, 0.9792, 0.4947],
        [0.3617, 0.9687, 0.0359]])

In [ ]:
a[0][0] = 0

In [ ]:
b

tensor([[0.0000, 0.9792, 0.4947],
        [0.3617, 0.9687, 0.0359]])

In [ ]:
a

tensor([[0.0000, 0.9792, 0.4947],
        [0.3617, 0.9687, 0.0359]])

In [ ]:
id(a)

133235392429696

In [ ]:
id(b)

133235392429696

In [ ]:
b = a.clone()

In [ ]:
b

tensor([[0.0000, 0.9792, 0.4947],
        [0.3617, 0.9687, 0.0359]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.9792,  0.4947],
        [ 0.3617,  0.9687,  0.0359]])

In [ ]:
b

tensor([[0.0000, 0.9792, 0.4947],
        [0.3617, 0.9687, 0.0359]])

In [ ]:
id(a)

133235392429696

In [ ]:
id(b)

133240488066368

## Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
device

device(type='cuda')

In [ ]:
# creating a tensor on GPU
x = torch.rand((2,3), device=device)
x


tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
a = torch.rand(3,3)

In [ ]:
b = a.to(device)

In [ ]:
b + 5

tensor([[5.3139, 5.1219, 5.3516],
        [5.2316, 5.2847, 5.3520],
        [5.2828, 5.2420, 5.4928]], device='cuda:0')

## Reshaping Tensors

In [ ]:
a = torch.ones(4,4)

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.1088, 0.7065, 0.0105, 0.4602],
         [0.2945, 0.0475, 0.6401, 0.3784],
         [0.5887, 0.0720, 0.9140, 0.0085]],

        [[0.2174, 0.1890, 0.0911, 0.6344],
         [0.3142, 0.7052, 0.6447, 0.9517],
         [0.3581, 0.3411, 0.0433, 0.4373]]])

In [ ]:
# permute
b.permute(2,0,1)

tensor([[[0.1088, 0.2945, 0.5887],
         [0.2174, 0.3142, 0.3581]],

        [[0.7065, 0.0475, 0.0720],
         [0.1890, 0.7052, 0.3411]],

        [[0.0105, 0.6401, 0.9140],
         [0.0911, 0.6447, 0.0433]],

        [[0.4602, 0.3784, 0.0085],
         [0.6344, 0.9517, 0.4373]]])

In [208]:
# unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [210]:
# squeeze
c.unsqueeze(0).squeeze(0).shape

torch.Size([226, 226, 3])

## NumPy and PyTorch

In [211]:
import numpy as np

In [212]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [216]:
b = a.numpy()

In [217]:
b

array([1, 2, 3])

In [218]:
type(b)

numpy.ndarray

In [219]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [221]:
d = torch.from_numpy(c)

In [223]:
type(d)

torch.Tensor